### ISSUE TITLE
Incomplete Code and Bugs in CrossBind.py 

### ISSUE THREAD

**Issue by 1874Mercury** [BEAM-Labs/CrossBind#1]
Hey there!

First off, great work on your paper! However, I took a look at the code you provided on GitHub, specifically the "CrossBind.py" training script, and it seems to be missing some crucial parts. On top of that, I spotted a few bugs in the code as well.

As someone who's really interested in your research, I was excited to try and reproduce the results from your paper and possibly even build upon your work. But, with the current state of the code and the bugs, I'm hitting a bit of a roadblock.

Would it be possible for you to take another look at the CrossBind.py script and fill in the missing pieces? It would be awesome if you could provide a complete and working version of the training script.

**Comment by jinglinglingling** [comment]
> Hey there!
> 
> First off, great work on your paper! However, I took a look at the code you provided on GitHub, specifically the "CrossBind.py" training script, and it seems to be missing some crucial parts. On top of that, I spotted a few bugs in the code as well.
> 
> As someone who's really interested in your research, I was excited to try and reproduce the results from your paper and possibly even build upon your work. But, with the current state of the code and the bugs, I'm hitting a bit of a roadblock.
> 
> Would it be possible for you to take another look at the CrossBind.py script and fill in the missing pieces? It would be awesome if you could provide a complete and working version of the training script.

Hi there, we now publish all training details in ProteinDecoy-main.py, and reserve examples for all required files (such as pdb -> xyz), all files can be obtained by following the steps in ReadMe, thanks.
